---
title: RuBrick
author: RuBrick
email: info@rubrick.ca
description: ComingSoon
baseurl: "/"
url: rubrick.ca
defaults:
- scope: ''
  values: ''
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
